version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=bdung
    expose:
      - '27017'
    volumes:
      - database:/data/db

  back:
    container_name: back
    image: m4vdoshin/helper_back:test
    command:
      python main.py
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    links:
      - mongodb
      
  nginx:
    container_name: front
    image: m4vdoshin/helper_front
    ports: 
      - "80:80"
    depends_on: 
      - back
    links: 
      - back
    restart: always

volumes:
  database:
    driver: local
