services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 10s
      retries: 30
    restart: always

  back:
    container_name: back
    build: back/.
    command: python main.py
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      
  nginx:
    container_name: front
    image: m4vdoshin/helper_front:test
    ports: 
      - "80:80"
    depends_on: 
      - back
    links: 
      - back
    restart: always

volumes:
  database:
    driver: local
